name: Deployment

on:
  push:
    branches: [main]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd test-env
          git pull origin main
          git status
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm install --only=prod
          pm2 restart app.js
